### PR TITLE
update to current 16.04 image

### PR DESCRIPTION
**Pull request by tjhei**
- change the Dockerfile to trigger a new build of dealii/ubuntu16 (the
current one is a year old and the apt-get sources are broken)
- install the locale package (now required)

### CODE REVIEW

**Comment by luca-heltai** [comment]
I don't know why the travis file is not happy about this changes. Maybe we simply didn't test it for too long... 

Can you try to figure out what's wrong with travis, and in case just remove the .travis.yml file? These are already being built on dockerhub...

**Comment by tjhei** [comment]
> Can you try to figure out what's wrong with travis, and in case just remove the .travis.yml file?

The error is "E: Package 'docker-engine' has no installation candidate"...

**Comment by tjhei** [comment]
This change might fix travis.

Do you still want travis to push the generated image? If not we should disable that...

**Comment by luca-heltai** [comment]
No, I think we should not use travis with the docker images. Can you remove the .travis.yml file?

**Comment by tjhei** [comment]
done.

**Pull request merged**
