### PR TITLE
Updated to v8.5.0

### PR DESCRIPTION
**Pull request by luca-heltai**
With this PR, fulldepscandi has the full dependency list enabled (except 64bits) and updated to latest candi release. 

I'm currently rebuilding all images. 

@tjhei Do you have any specific reason to have zlib installed within candi instead of using apt-get from ubuntu?

### CODE REVIEW

**Comment by luca-heltai** [comment]
This partially overlaps with #10 (I started working on this this morning, and when I got to hit the PR button, I saw your other PR...). I'll let you decide what to do. The makefile currently builds and push to `dealii/*` if you hit 

~~~
make all
~~~

I'm waiting for the compilations of all images to finish, and then I'll push each one to docker hub.

**Comment by tjhei** [comment]
> @tjhei Do you have any specific reason to have zlib installed within candi instead of using apt-get from ubuntu?

No. ``apt-get`` would be the better solution, but I didn't want to touch the packages to be installed. Do you want me to change that?

**Comment by tjhei** [comment]
> (except 64bits)

Are you talking about a 64bit int PETSc? How do you want to handle this, install both next to each other?

**Comment by luca-heltai** [comment]
This apparently passed on travis (using serial bare configs), but every time I try to build deal.II with the candi configuration, I get a memory exhaustion problem:

~~~
/vector_tools_integrate_difference.cc.o.d -o source/numerics/CMakeFiles/obj_numerics_debug.dir/vector_tools_integrate_difference.cc.o -c ../source/numerics/vector_tools_integrate_difference.cc
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
[600/1266] Building CXX object source/numerics/CMakeFiles/obj_numerics_debug.dir/data_out_faces.cc.o
[601/1266] Building CXX object source/numerics/CMakeFiles/obj_numerics_debug.dir/vector_tools_constraints.cc.o
[602/1266] Building CXX object source/numerics/CMakeFiles/obj_numerics_debug.dir/vector_tools_interpolate.cc.o
ninja: build stopped: subcommand failed.
The command '/bin/sh -c git clone https://github.com/dealii/dealii.git dealii-$VER-src &&     cd dealii-$VER-src &&     git checkout $VER &&     mkdir build && cd build &&     cmake -DDEAL_II_WITH_MPI=ON           -DDEAL_II_COMPONENT_EXAMPLES=OFF           -DCMAKE_INSTALL_PREFIX=~/dealii-$VER           -DCMAKE_BUILD_TYPE=$BUILD_TYPE 	  -GNinja           ../ &&     ninja install &&     ninja test &&     cp summary.log ~/dealii-$VER/summary.log &&     cd .. && rm -rf build .git' returned a non-zero code: 1
~~~

**Comment by luca-heltai** [comment]
With the current `fulldeps-candi`, we manage to get the following `summary.log`:

~~~
###
#
#  deal.II configuration:
#        CMAKE_BUILD_TYPE:       DebugRelease
#        BUILD_SHARED_LIBS:      ON
#        CMAKE_INSTALL_PREFIX:   /home/dealii/dealii-v8.5.0
#        CMAKE_SOURCE_DIR:       /home/dealii/dealii-v8.5.0-src
#                                (version 8.5.0, shortrev 007eaa5)
#        CMAKE_BINARY_DIR:       /home/dealii/dealii-v8.5.0-src/build
#        CMAKE_CXX_COMPILER:     GNU 6.2.0 on platform Linux x86_64
#                                /usr/bin/mpicxx
#
#  Configured Features (DEAL_II_ALLOW_BUNDLED = ON, DEAL_II_ALLOW_AUTODETECTION = ON):
#      ( DEAL_II_WITH_64BIT_INDICES = OFF )
#        DEAL_II_WITH_ARPACK set up with external dependencies
#        DEAL_II_WITH_BOOST set up with bundled packages
#        DEAL_II_WITH_BZIP2 set up with external dependencies
#        DEAL_II_WITH_CXX11 = ON
#        DEAL_II_WITH_CXX14 = ON
#        DEAL_II_WITH_GSL set up with external dependencies
#        DEAL_II_WITH_HDF5 set up with external dependencies
#        DEAL_II_WITH_LAPACK set up with external dependencies
#        DEAL_II_WITH_METIS set up with external dependencies
#        DEAL_II_WITH_MPI set up with external dependencies
#        DEAL_II_WITH_MUPARSER set up with bundled packages
#        DEAL_II_WITH_NETCDF set up with external dependencies
#        DEAL_II_WITH_OPENCASCADE set up with external dependencies
#        DEAL_II_WITH_P4EST set up with external dependencies
#        DEAL_II_WITH_PETSC set up with external dependencies
#        DEAL_II_WITH_SLEPC set up with external dependencies
#        DEAL_II_WITH_THREADS set up with bundled packages
#        DEAL_II_WITH_TRILINOS set up with external dependencies
#        DEAL_II_WITH_UMFPACK set up with bundled packages
#        DEAL_II_WITH_ZLIB set up with external dependencies
#
#  Component configuration:
#      ( DEAL_II_COMPONENT_DOCUMENTATION = OFF )
#      ( DEAL_II_COMPONENT_EXAMPLES = OFF )
#      ( DEAL_II_COMPONENT_PACKAGE = OFF )
#      ( DEAL_II_COMPONENT_PYTHON_BINDINGS = OFF )
#
#  Detailed information (compiler flags, feature configuration) can be found in detailed.log
#
#  Run  $ ninja info  to print a help message with a list of top level targets
#
###
~~~

**Comment by luca-heltai** [comment]
I'm pushing the latest build. It will take some time from my adsl connection... :) 

What I meant is that the only disabled option is

~~~
 ( DEAL_II_WITH_64BIT_INDICES = OFF )
~~~

But I think this is fine. Opinions?

**Comment by luca-heltai** [comment]
@tjhei 

> No. apt-get would be the better solution, but I didn't want to touch the packages to be installed. Do you want me to change that?

this PR already does that. I rebuilt all the base images. I'm waiting for the dealii with fulldepsmanual to build. I think we should clean things up, and remove all the various options, now that candi was updated.

It makes no sense to have a `fulldepsmanual` and `fulldepscandi`. I vote to keep the candi version only. I'll open an issue.

**Comment by tjhei** [comment]
> But I think this is fine. Opinions?

Yes.

> I vote to keep the candi version only.

agreed.

**Pull request merged**
