### PR TITLE
[RFC] Used to generate working images on dockerhub

### PR DESCRIPTION
**Pull request by luca-heltai**
This is my rework, used to generate all images under heltai/... on docker hub

### CODE REVIEW

**Comment by luca-heltai** [comment]
@tjhei, I don't know if candi is the way to go, or if we should go for the manual configuration, or, better yet, keep both versions and add may be a spack version? What do people think?

**Comment by tjhei** [comment]
I like using it for several reasons:
1. Why rewrite scripts to download and install if they already exist?
2. Keeping scripts updated (new library versions, patches, etc.) means duplicated work.
3. This serves as a testbed for candi.
4. We would have an identical setup for a) docker b) virtual machine c) user installs d) unit tests (at least for ASPECT for now).

**Comment by Rombur** [comment]
In my group we use docker to run our test suite so we try to have containers with different configurations. I am in the process of creating a new container with spack and clang. If you are interested, I can add it here too.

Something that we should also think about is to run the test suite with deal installed in a container. We recently had a bug that would only appear when using docker. With a native install everything was working fine even though the code was wrong.

**Comment by tjhei** [comment]
> I am in the process of creating a new container with spack and clang. If you are interested, I can add it here too.

Then we have three instead of two options, which is two too many. :-)

> Something that we should also think about is to run the test suite with deal installed in a container.

I would like to do exactly that like I already do for ASPECT (running it as a continuous integration thing). It would just be a matter of having a machine and setting it up. Of course we won't be able to test all kinds of configurations. It is easier with ASPECT because we have one "minimum spec".

**Comment by luca-heltai** [comment]
I think having three options is just fine, and at least until we have a solution that works for every possible configuration (and platform!), we should not reject other solutions. Candi is an alternative to `spack`, with much fewer options, and which does not work on a mac. I'm personally not inclined in using a tool that can only work on one platform, and I also think that there is good in showing explicitly how to compile the different libraries in a single script. Having a reference place to send people who ask is also good. Maybe this should not be the default, I agree. 
Then I'd be inclined to choose something like spack instead of candi.

**Comment by luca-heltai** [comment]
@Rombur , what's the status of your docker image? I'd like to either merge Timo's version, or yours. I don't fully agree with Timo, but in the end our different views have simply stopped this repository from being useful, and everybody kept doing what they were doing before... I'd like to change that...

We should have official docker images for deal.II. Some of us are using unofficial ones happily and succesfully. For example on our own travis-based infrastructure (see https://github.com/mathLab/pi-DoMUS, we use my docker images with Travis to run a fully featured installation of deal.II), but I'd like to push one solution forward, either candi or spack, and make an official image with a full-fledged deal.II.

@tjhei 's solution is still missing some packages, like arpack, netcdf, gsl...

**Comment by Rombur** [comment]
@luca-heltai unfortunately, I got sidetracked. You should merge Timo's version.

**Pull request closed without merging**
